on: [push]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 16 * * *'
jobs:
  create_issues_action:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: create issues action
        uses:  pengtaoa/create-issues-action@main
        with:
          token: ${{secrets.TOKEN}}
       # Use the output from the `hello` step
      # - name: Get the output time
      #  run: echo "The time was ${{ steps.hello.outputs.time }}"